{
    "name": "InfoHub Email Channel",
    "summary": "Receive newsletter email into the InfoHub pool",
    "version": "19.0.1.0.0",
    "author": "quick-sort@outlook.com",
    "website": "quick-sort@outlook.com",
    "license": "LGPL-3",
    "category": "Productivity",
    "depends": ["infohub", "mail", "infohub_agent"],
    "data": [
        "security/ir.model.access.csv",
        "data/mail_alias.xml",
        "data/llm_agent_data.xml",
        "views/infohub_channel_views.xml",
        "views/infohub_email_message_views.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}
