"""Contextual-retrieval splitter.

Splits text the same way the recursive splitter does, then prefixes each
resulting chunk with a short situating context describing where it sits in
the source document -- the "contextual retrieval" technique (see
https://www.anthropic.com/news/contextual-retrieval): embedding
``context + "\\n\\n" + chunk`` instead of the raw chunk improves retrieval
because the embedding captures document-level context a chunk alone would
lose.

The context is generated by a chat-capable ``llm.model``, configured on the
splitter's ``context_model_id`` field. If no model is configured, or the
chat call fails, this degrades gracefully to a static prefix built from the
resource name -- callers should not have to handle a hard failure just
because contextual generation is unavailable.
"""

import logging

from odoo.addons.component.core import Component

_logger = logging.getLogger(__name__)

_CONTEXT_PROMPT = (
    "You are indexing a document for semantic search. Given the full "
    "document and one chunk extracted from it, write a short (1-2 "
    "sentence) context blurb that situates the chunk within the overall "
    "document, so that embedding the blurb + chunk together retrieves "
    "better than the chunk alone. Answer with only the blurb, no preamble."
)


class ContextualSplitter(Component):
    _name = "llm.contextual.splitter"
    _inherit = "llm.knowledge.splitter.component"
    _usage = "contextual"

    def split(self, text, **context):
        base_chunks = self._recursive_split(text)
        resource = context.get("resource")
        model = self.collection.context_model_id
        if not model or not base_chunks:
            return base_chunks
        document_title = resource.name if resource else ""
        return [
            self._wrap_with_context(model, text, chunk, document_title)
            for chunk in base_chunks
        ]

    def _recursive_split(self, text):
        """Reuse the recursive splitter's algorithm for the base chunking;
        the contextual wrapping is applied on top of its output."""
        recursive = self.env["llm.knowledge.splitter"].browse(self.collection.id)
        with recursive.work_on("llm.knowledge.splitter") as work:
            adapter = work.component(usage="recursive")
        return adapter.split(text)

    def _wrap_with_context(self, model, document_text, chunk, document_title):
        blurb = self._generate_context_blurb(model, document_text, chunk, document_title)
        return f"{blurb}\n\n{chunk}" if blurb else chunk

    def _generate_context_blurb(self, model, document_text, chunk, document_title):
        try:
            # Keep the prompt bounded: a full multi-MB document would blow
            # past context windows and cost, so cap what we send.
            truncated_document = document_text[:8000]
            messages = [
                {"role": "system", "content": _CONTEXT_PROMPT},
                {
                    "role": "user",
                    "content": (
                        f"<document title=\"{document_title}\">\n"
                        f"{truncated_document}\n"
                        "</document>\n\n"
                        f"<chunk>\n{chunk}\n</chunk>"
                    ),
                },
            ]
            response = model.chat(messages)
            return self._extract_text(response)
        except Exception:  # noqa: BLE001
            _logger.warning(
                "Contextual splitter: falling back to static prefix "
                "(context generation failed)",
                exc_info=True,
            )
            return f"From document: {document_title}." if document_title else ""

    @staticmethod
    def _extract_text(response):
        if isinstance(response, str):
            return response.strip()
        if isinstance(response, dict):
            # Common shapes: {"content": "..."} or
            # {"choices": [{"message": {"content": "..."}}]}
            if "content" in response:
                return str(response["content"]).strip()
            choices = response.get("choices") or []
            if choices:
                message = choices[0].get("message") or {}
                return str(message.get("content", "")).strip()
        return str(response).strip()
