{
    "name": "LLM Knowledge",
    "summary": "Knowledge ingestion, chunking, vector indexing, and retrieval",
    "description": """
        Manages source-backed knowledge collections, binary retrieval, Markdown
        extraction, reusable chunksets, vector-store instances, logical vector
        databases, provider record ownership, and configurable BM25/dense/sparse/
        hybrid query interfaces.
    """,
    "category": "Technical",
    "version": "19.0.7.0.0",
    "depends": ["llm", "component", "storage_backend", "queue_job"],
    "external_dependencies": {"python": ["requests"]},
    "author": "quick-sort@outlook.com",
    "website": "quick-sort@outlook.com",
    "data": [
        "security/ir.model.access.csv",
        "data/server_actions.xml",
        "data/ir_cron_data.xml",
        "views/llm_document_views.xml",
        "views/llm_document_extractor_views.xml",
        "views/llm_document_extractor_mapping_views.xml",
        "views/llm_knowledge_collection_views.xml",
        "wizards/upload_document_wizard_views.xml",
        "views/llm_document_menu.xml",
        "views/menu.xml",
        "views/llm_store_views.xml",
        "views/llm_store_database_record_views.xml",
        "views/llm_store_database_query_views.xml",
        "views/llm_store_database_views.xml",
        "views/llm_store_menu_views.xml",
        "views/llm_knowledge_splitter_views.xml",
        "views/llm_knowledge_chunkset_views.xml",
        "views/llm_knowledge_vector_views.xml",
        "views/llm_store_chunk_views.xml",
        "views/llm_knowledge_collection_store_views.xml",
        "views/llm_document_store_views.xml",
        "views/store_menu.xml",
    ],
    "demo": [
        "data/llm_knowledge_demo.xml",
        "data/llm_knowledge_splitter_demo.xml",
        "data/llm_knowledge_vector_demo.xml",
    ],
    "images": ["static/description/banner.jpeg"],
    "license": "LGPL-3",
    "installable": True,
    "application": False,
    "auto_install": False,
}
