{
    "name": "LLM PostgreSQL pgvector Capability",
    "summary": "Add dense and sparse pgvector storage to managed PostgreSQL databases",
    "category": "Technical",
    "version": "19.0.3.0.0",
    "author": "quick-sort@outlook.com",
    "depends": ["llm_pg"],
    "external_dependencies": {"python": ["psycopg2"]},
    "data": ["data/llm_pg_capability.xml"],
    "images": ["static/description/banner.jpeg"],
    "license": "LGPL-3",
    "installable": True,
    "application": False,
    "auto_install": False,
}
