{
    "name": "InfoHub",
    "summary": "Aggregate news from many sources through pluggable channels",
    "version": "19.0.1.0.0",
    "author": "quick-sort@outlook.com",
    "website": "quick-sort@outlook.com",
    "license": "LGPL-3",
    "category": "Productivity",
    "depends": ["base", "component", "queue_job"],
    "data": [
        "security/infohub_security.xml",
        "security/ir.model.access.csv",
        "data/queue_data.xml",
        "data/ir_cron_data.xml",
        "views/infohub_item_views.xml",
        "views/infohub_channel_views.xml",
        "views/infohub_source_views.xml",
        "views/infohub_menus.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
}
