#!/usr/bin/env python3
"""Write a requirements.txt into every addon.

Each file lists the Python packages that addon needs at runtime, so a
deployment can install only what the addons it actually uses require:

    pip install -r infohub_channel_rss/requirements.txt

Odoo itself never reads these files -- it only checks ``external_dependencies``
in ``__manifest__.py``. They exist for humans and tooling.

Provenance
----------

Each entry comes from one of three places, and is annotated with which:

``# no comment``
    ``external_dependencies.python`` from the manifest. This is the contract the
    addon declares, and it wins on conflict.

``# undeclared``
    Imported at *module* level somewhere in the addon but absent from the
    manifest. A real runtime requirement that would otherwise crash the addon on
    import; the gap should be fixed upstream in the manifest.

``# needed by Odoo to parse the manifest``
    Required by Odoo itself, not the addon. ``check_python_external_dependency``
    uses ``packaging`` to parse any requirement carrying a version specifier and
    fails with a confusing error when it is missing.

An import inside a function body is not treated as a runtime requirement: the
codebase uses that pattern deliberately for optional features (see the
``Dockerfile.odoo`` note about boto3 / openpyxl / azure). ``tests/`` and ``doc/``
are skipped -- those are development dependencies, not runtime ones.

Usage::

    python3 scripts/generate_requirements.py           # write files
    python3 scripts/generate_requirements.py --check   # fail if out of date
"""

import argparse
import ast
import io
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

#: Directories never scanned for runtime imports.
SKIP_DIRS = {"__pycache__", ".git", "tests", "doc", "migrations", "static"}

#: Import name -> PyPI distribution name, where they differ. Odoo resolves
#: external dependencies through importlib.metadata, so the manifest is expected
#: to carry PyPI names -- passing one through unchanged is the common case.
PYPI_NAMES = {
    "yaml": "PyYAML",
    "dateutil": "python-dateutil",
    "PIL": "Pillow",
    "qdrant_client": "qdrant-client",
    "jinja2": "Jinja2",
    "werkzeug": "Werkzeug",
    "bs4": "beautifulsoup4",
    "sphinx_bootstrap_theme": "sphinx-bootstrap-theme",
    "vcr": "vcrpy",
}

#: Modules provided by Odoo itself, or by the base image as part of the
#: interpreter's standard deployment. Never listed.
IGNORED = {"odoo", "lxml"}

HEADER = """\
# Generated by scripts/generate_requirements.py -- do not edit by hand.
#
# Runtime dependencies for the {addon} addon. Odoo does not read this file; it
# checks `external_dependencies` in __manifest__.py, which is where these come
# from. Kept in sync from the manifest and from module-level imports.
#
# Install with:  pip install -r {addon}/requirements.txt
"""


def _manifest_path(addon_dir):
    return os.path.join(addon_dir, "__manifest__.py")


def declared_dependencies(addon_dir):
    """``external_dependencies.python`` from the manifest, in declared order."""
    path = _manifest_path(addon_dir)
    try:
        manifest = ast.literal_eval(io.open(path, encoding="utf-8").read())
    except (SyntaxError, ValueError):
        return []
    external = manifest.get("external_dependencies") or {}
    return list(external.get("python") or [])


def imported_modules(addon_dir):
    """Top-level third-party modules imported anywhere in the addon."""
    found = set()
    for root, dirs, files in os.walk(addon_dir):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
        for name in files:
            if not name.endswith(".py"):
                continue
            try:
                tree = ast.parse(
                    io.open(os.path.join(root, name), encoding="utf-8").read()
                )
            except (SyntaxError, UnicodeDecodeError):
                continue
            # Only module-level statements. A deferred import inside a function
            # marks an optional feature, not a runtime requirement.
            for node in tree.body:
                found.update(_module_names(node))
    return {m for m in found if m not in IGNORED and m not in sys.stdlib_module_names}


def _module_names(node):
    names = set()
    if isinstance(node, ast.Import):
        names.update(alias.name.split(".")[0] for alias in node.names)
    elif isinstance(node, ast.ImportFrom) and node.level == 0 and node.module:
        names.add(node.module.split(".")[0])
    # Imports inside a module-level `try:` block (the usual optional-dependency
    # guard) still run at import time, so they count.
    elif isinstance(node, ast.Try):
        for child in node.body:
            names.update(_module_names(child))
    return names


def _distribution_name(requirement):
    """The bare distribution name from a requirement line.

    A manifest entry may carry extras and a version specifier
    ("pydantic>=2.0.0", "psycopg2[binary]") while the import is just the module
    name, so comparison happens on the name alone.
    """
    return (
        requirement.split(">=")[0]
        .split("==")[0]
        .split("!=")[0]
        .split("<")[0]
        .split(">")[0]
        .split("[")[0]
        .strip()
    )


#: Explains why a package is listed without being declared in the manifest.
UNDECLARED_IMPORT = "undeclared"
NEEDED_BY_ODOO = "needed by Odoo to parse the manifest"


def build_requirements(addon_dir):
    """Return ``(declared_lines, [(name, reason), ...])`` for one addon."""
    declared = declared_dependencies(addon_dir)
    # Names already covered by a declaration, compared case-insensitively so
    # "pyyaml" and the import's "PyYAML" are recognised as the same package.
    seen = {_distribution_name(d).lower() for d in declared}

    extras = []
    for module in sorted(imported_modules(addon_dir)):
        pypi = PYPI_NAMES.get(module, module)
        if pypi.lower() in seen or module.lower() in seen:
            continue
        seen.add(pypi.lower())
        extras.append((pypi, UNDECLARED_IMPORT))

    # `packaging` is required by Odoo itself rather than by the addon:
    # check_python_external_dependency() uses it to parse any requirement
    # carrying a version specifier, and fails with a confusing "Package
    # `packaging` is required to parse ..." error when it is missing. The base
    # image does not ship it, so an addon declaring "pydantic>=2.0.0" cannot be
    # installed until it is present.
    if any(any(c in dep for c in "<>=!") for dep in declared) and "packaging" not in seen:
        extras.append(("packaging", NEEDED_BY_ODOO))

    return list(declared), extras


def render(addon, declared, extras):
    out = [HEADER.format(addon=addon)]
    if declared:
        out.append("# Declared in __manifest__.py external_dependencies.")
        out.extend(declared)
    if extras:
        if declared:
            out.append("")
        out.append(
            "# Not declared in __manifest__.py. Each line says why it is here\n"
            "# anyway; the '# undeclared' ones belong in the manifest so Odoo\n"
            "# checks them too."
        )
        out.extend(f"{name}  # {reason}" for name, reason in extras)
    if not declared and not extras:
        out.append("# No runtime dependencies beyond the Odoo base image.")
    return "\n".join(out) + "\n"


def iter_addons():
    for name in sorted(os.listdir(REPO_ROOT)):
        addon_dir = os.path.join(REPO_ROOT, name)
        if not os.path.isdir(addon_dir) or name.startswith("."):
            continue
        if name in ("scripts", "legacy"):
            continue
        if os.path.isfile(_manifest_path(addon_dir)):
            yield name, addon_dir


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if any file is missing or out of date",
    )
    args = parser.parse_args()

    stale = []
    for addon, addon_dir in iter_addons():
        declared, extras = build_requirements(addon_dir)
        content = render(addon, declared, extras)
        target = os.path.join(addon_dir, "requirements.txt")

        current = None
        if os.path.isfile(target):
            current = io.open(target, encoding="utf-8").read()

        if current == content:
            continue
        if args.check:
            stale.append(addon)
            continue
        io.open(target, "w", encoding="utf-8").write(content)
        marker = "updated" if current else "created"
        print(f"  {marker}: {addon}/requirements.txt")

    if args.check and stale:
        print("out of date: " + ", ".join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
