{
    "name": "Async Task",
    "summary": "Component-driven lifecycle for local and remote asynchronous tasks",
    "version": "19.0.1.0.0",
    "author": "quick-sort@outlook.com",
    "license": "LGPL-3",
    "category": "Technical",
    "depends": ["base", "component", "queue_job"],
    "data": [
        "security/async_task_security.xml",
        "security/ir.model.access.csv",
        "data/queue_data.xml",
        "data/cron_data.xml",
        "views/async_task_views.xml",
        "views/async_task_menus.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
}
